language: java
script: mvn clean package
deploy:
  provider: releases
  api_key:
    secure: MvVgC3LoiTB5rzoYI84Gig4gekB9bm6L5SdYr30xR8Na1B3z5Lh6tEIxEbP+6RHmM1UyFSkD+p+OA3gN6a7kL7PMyTTG/j9mWcnGmb6VaWzS4d3GlW/nR5+ulmuA3mE5eB4gVUXfcKl5zYX00XLfoGtARYumEaMpVOia9NA1gSg=
  file: target/releases/elasticsearch-analysis-string2int-*.zip
  file_glob: true
  on:
    repo: medcl/elasticsearch-analysis-string2int
    tags: true

